apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

generators:
  - ksops-generator.yaml

patches:
  - path: deployment_resources_patch.yaml

resources:
  - ../base/
