apiVersion: v1
kind: Secret
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/instance: hello-world
    app.kubernetes.io/version: 1.16.0
type: Opaque
data:
  username: dXNlcm5hbWUtZGV2
  password: cGFzc3dvcmQtZGV2
